### PR TITLE
Oracle Manager UI Github Icon

### PR DESCRIPTION
**Pull request by fritzschoff**

### CODE REVIEW

**Review by noahlitvin — APPROVED** [review]

**Comment by bachstatter** [comment]
@fritzschoff  Please don't merge if CI is failing
https://app.circleci.com/pipelines/github/Synthetixio/js-monorepo/1768/workflows/db413cbd-3b07-4c96-bea2-849cb5d69f40/jobs/8661
image

The icons not using proper react props

**Comment by fritzschoff** [comment]
> @fritzschoff Please don't merge if CI is failing https://app.circleci.com/pipelines/github/Synthetixio/js-monorepo/1768/workflows/db413cbd-3b07-4c96-bea2-849cb5d69f40/jobs/8661 image
> 
> The icons not using proper react props

@bachstatter 
Bildschirm­foto 2023-01-17 um 09 32 57
not want to blame on Noah but didn't pressed the button ☮️

**Comment by fritzschoff** [comment]
> > @fritzschoff Please don't merge if CI is failing https://app.circleci.com/pipelines/github/Synthetixio/js-monorepo/1768/workflows/db413cbd-3b07-4c96-bea2-849cb5d69f40/jobs/8661 image
> > The icons not using proper react props
> 
> @bachstatter Bildschirm­foto 2023-01-17 um 09 32 57 not want to blame on Noah but didn't pressed the button ☮️

**Comment by fritzschoff** [comment]
> @fritzschoff Please don't merge if CI is failing https://app.circleci.com/pipelines/github/Synthetixio/js-monorepo/1768/workflows/db413cbd-3b07-4c96-bea2-849cb5d69f40/jobs/8661 image
> 
> The icons not using proper react props

+ this isn't even the recent commit on this branch.... so please !

**Comment by bachstatter** [comment]
> > @fritzschoff Please don't merge if CI is failing https://app.circleci.com/pipelines/github/Synthetixio/js-monorepo/1768/workflows/db413cbd-3b07-4c96-bea2-849cb5d69f40/jobs/8661 image
> > The icons not using proper react props
> 
> * this isn't even the recent commit on this branch.... so please !

Sorry I was on the hunt for why deps got downgraded saw a red x and wrote a bit too quickly.  My mistake 🙏

**Pull request merged**
