### PR TITLE
feat(data): add exchangeEntrySettled query

### PR DESCRIPTION
**Pull request by vbstreetz**

### CODE REVIEW

**Review by JChiaramonte7 — APPROVED** [review]
LGTM but thoughts @dvd-schwrtz @KillerByte ?

**Review by KillerByte — APPROVED** [review]
as long as tests are passing and things are checked on your end :+1:

**Comment by vbstreetz** [comment]
Screenshot 2021-07-16 at 21 51 47

🤔

**Comment by KillerByte** [comment]
@vbstreetz yea the ci is currently broken on the monorepo, just ignore it.

but locally just run the tests and make sure they succeed is all.

**Comment by vbstreetz** [comment]
awesome

**Comment by vbstreetz** [comment]
Screenshot 2021-07-19 at 17 04 21
 Looking good ... merged ...

**Pull request merged**
