### PR TITLE
feature/implement-stats-V3-from-Dune

### PR DESCRIPTION
**Pull request by duyentb95**

### CODE REVIEW

**Comment by duyentb95** [comment]
Any review feedback for this PR?

**Comment by jmzwar** [comment]
Hi @duyentb95 looking really good. A couple of minor things.

The background on the v2/v3 selector extends out beyond the content - see attached.

Screen Shot 2023-10-15 at 10 11 47 am

Also - let's rename some of the labels both on the graphs and in the tooltips.

TVL Protocols:
=> capitalise 'ethereum' and 'optimism' to 'Ethereum' and 'Optimism' in both the legend and tooltip.

TVL Layer
=> Rename 'ethSNX' and 'opSNX' to 'Ethereum SNX' and 'Optimism SNX' respectively (both legend and tooltip).

Historical Delegations & Daily Delegations
=> Remove dashes and capitalise ethereum and optimism respectively (both legend and tooltip)

SNX Supply daily mint and burn
=> Legend - replace to Ethereum SNX Supply and Optimism SNX Supply
=> Tooltip - replace to Ethereum Mints | Optimism Mints | Ethereum Burns | Optimism Burns etc ...

Super high quality PR

**Comment by duyentb95** [comment]
Hi @jmzwar! Thank you for your review and feedback!
I have updated the PR with edits according to your comments ^^
https://github.com/Synthetixio/js-monorepo/pull/986/commits/966eff1484aa85b7150b492015432f90117871a1

**Comment by jmzwar** [comment]
Hey! Looks like there are some conflicts that may need to be resolved. Lmk if you need help.

**Comment by duyentb95** [comment]
> Hey! Looks like there are some conflicts that may need to be resolved. Lmk if you need help.

Hi @jmzwar ! Authentication required to write access to this repository can resolve conflicts & merge pull request.

**Comment by duyentb95** [comment]
@jmzwar @noisekit Thank you for your help! I was resolved conflicts and updated this PR.

**Comment by jmzwar** [comment]
> @jmzwar @noisekit Thank you for your help! I was resolved conflicts and updated this PR.

Awesome - it looks like the build is still failing. Can you try running locally `yarn install --immutable --immutable-cache`

**Comment by duyentb95** [comment]
> > @jmzwar @noisekit Thank you for your help! I was resolved conflicts and updated this PR.
> 
> Thanks - it looks like the build is still failing though. Can you try running locally `yarn install --immutable --immutable-cache`

@jmzwar I am try running locally `yarn install --immutable --immutable-cache` and the build is still failing with `yarn dedupe --check
`
Now what should I do next?  

Screen Shot 2023-10-23 at 08 22 43

Screen Shot 2023-10-23 at 07 51 13

**Comment by jmzwar** [comment]
> Screen Shot 2023-10-23 at 08 51 52

Could you try `yarn deps --fix` from the root of the project

**Comment by duyentb95** [comment]
> > Screen Shot 2023-10-23 at 08 51 52
> 
> Could you try `yarn deps --fix` from the root of the project

@jmzwar Yep, I was read config.yml to try fix the build for [check] section but I am still get error for [v2-e2e] section.

Screen Shot 2023-10-23 at 17 51 15
Screen Shot 2023-10-23 at 17 37 07

**Comment by jmzwar** [comment]
> > > Screen Shot 2023-10-23 at 08 51 52
> > 
> > 
> > Could you try `yarn deps --fix` from the root of the project
> 
> @jmzwar Yep, I was read config.yml to try fix the build for [check] section but I am still get error for [v2-e2e] section.
> 
> Screen Shot 2023-10-23 at 17 51 15 Screen Shot 2023-10-23 at 17 37 07

Ah - because the id won't exist on your fork. Should be good no e2e on perps-ui.

**Pull request merged**
