### PR TITLE
feature/error handling bad search

### PR DESCRIPTION
**Pull request by Steve-Rog**
Error handling if a user enters an invalid address or invalid ens. 
- The edges of the searchbar highlight red and do not allow the user to complete the search

### CODE REVIEW

**Comment by jmzwar** [comment]
@Steve-Rog Looks like this has some conflicts that need to be resolved.

**Comment by Steve-Rog** [comment]
> @Steve-Rog Looks like this has some conflicts that need to be resolved.

Committed changes [here](https://github.com/Synthetixio/js-monorepo/pull/969)

**Comment by jmzwar** [comment]
@Steve-Rog Can close this now

**Comment by jmzwar** [comment]
@Steve-Rog Closing this as we merged another

**Pull request closed without merging**
