### PR TITLE
call out redemption amount

### PR DESCRIPTION
**Pull request by jmzwar**
Screenshot 2024-06-20 at 4 01 02 PM

=> Multiply balance by discount
=> Add tooltip to explain

### CODE REVIEW

**Comment by kaleb-keny** [comment]
potentially another bug 
Screenshot from 2024-06-20 14-03-26

**Comment by kaleb-keny** [comment]
hello sir @jmzwar susd does not have a discount 
Screenshot from 2024-06-24 15-21-54

**Comment by kaleb-keny** [comment]
hey @jmzwar few things maybe, 
- can we change the $ sign to sUSD please
- can we update the price to be the post redemption price (to avoid confusion)
other than that, lgtm

**Comment by kaleb-keny** [comment]
Screenshot from 2024-06-26 08-26-27
i guess dropping the amount below "274401.80 sUSD" makes sense

**Comment by jmzwar** [comment]
> Screenshot from 2024-06-26 08-26-27 i guess dropping the amount below "274401.80 sUSD" makes sense ... Also the 0% 😅 needs an update, it's not a redemption, leave it blank? And finally the header we spoke of in discord, to nudge users to discord to ask for redemption at parity. `If users wish to be redeemed at parity, users can request it from synthetix governance on discord, but this can only be fullfilled, if no redemption is performed by the user.`

Updated ser
Screenshot 2024-06-26 at 2 59 04 PM

**Review by kaleb-keny — APPROVED** [review]

**Pull request merged**
