### PR TITLE
Use png for curve icon

### PR DESCRIPTION
**Pull request by bachstatter**
- 6kb vs 274kb
Screen Shot 2022-10-28 at 7 58 16 am

### CODE REVIEW

**Comment by jmzwar** [comment]
Did you check if this looks decent on retina?

I am always super reluctant to use raster images.

**Comment by bachstatter** [comment]
> Did you check if this looks decent on retina?
> 
> I am always super reluctant to use raster images.

I looks a little bit worse. I exported it 2x the size though

**Comment by jmzwar** [comment]
Ok let me put my glasses on

**Comment by jmzwar** [comment]
It does look quite rasterised. 
I get that the file is huge but there is no performance hit in rendering it - can we just leave it for now?

**Comment by bachstatter** [comment]
> It does look quite rasterised. I get that the file is huge but there is no performance hit in rendering it - can we just leave it for now?

Hmm yea maybe she should just use it as a real SVG + img tag, so we dont add 270kb extra for react/js to parse

**Comment by jmzwar** [comment]
I'd be happy with that. Leave it to me and I can add it here

**Review by bachstatter — COMMENTED** [review]
Looks good to me

**Comment by jmzwar** [comment]
> Isn't it still way too big?

Yeah, but it's all lines, so raster makes it look pixellated.

**Pull request merged**
