### PR TITLE
Account navigation

### PR DESCRIPTION
**Pull request by 0xjocke**
- If your on the home page and switch to an address with accounts -> navigate to account page. Previously it only worked on reload.
- If you're on a page that requires account and switch to a wallet without accounts -> navigate to home

### CODE REVIEW

**Review by noisekit — APPROVED** [review]

**Comment by sunnyvempati** [comment]
@bachstatter it's actually by design that we want users to navigate to account pages without needing to be signed in.  the idea is anyone can go to anyone's account and view the data; we have some conditionally rendering components within the components that remove functionality if you don't have an account attached (there's more work to be done regarding this on the page itself; but think of this is as a view vs. write page)  cc @noahlitvin

**Comment by noahlitvin** [comment]
👍 This is correct. Views for all entities in all networks should be accessible regardless of wallet status. We just have a little bit of logic to decide where to kick you when loading the root path.

**Comment by bachstatter** [comment]
Yea ok we were all a little confused when switching wallets.  
So to clarify:
Say I have two wallets with staking positions. If I'm connected to one of them and switch to the other wallet the app will stay on the same page, (and I guess be in read only) for the previous wallet rather than showing the connected wallets account?

And if I have two wallets, one with a position and one without. If I'm looking at my position -> switch to the wallet without an account we want to say on the position page rather than navigating to home?

I do like the idea of having all pages accessible, but I think many users are used to the app reflecting/ updating when switching the connected wallet

**Comment by noahlitvin** [comment]
I was imagining the relevant functionality would just be disabled, you could navigate back to home from the top nav or 'account overview' link. I see where you're coming from though, maybe it's more natural to treat wallet change as like you've logged out and logged back in.

**Comment by bachstatter** [comment]
> I was imagining the relevant functionality would just be disabled, you could navigate back to home from the top nav or 'account overview' link. I see where you're coming from though, maybe it's more natural to treat wallet change as like you've logged out and logged back in.

Yea I think changing a wallet if more like a logout login to me.. To get some real benefit of the not connected state I think we need to have a way to search/ add wallet or accounts too.

**Pull request closed without merging**
