### PR TITLE
Removing tabs

### PR DESCRIPTION
**Pull request by sunnyvempati**

### CODE REVIEW

**Review by noisekit — APPROVED** [review]
So much for that 🤌
But please wait for someone else to chime in

**Comment by bachstatter** [comment]
haha I never had a strong opinion about this eternal debate. But I thought tabs was superior from an accessibility standpoint, cant you the tab width to whatever you like in your editor?

**Comment by bachstatter** [comment]
Yea ok. haha I never think about it, haven't experienced reformatting json. Either way if you two think the benefits with spaces is worth having a commit with sunny's name on every file, go for it :)

**Comment by sunnyvempati** [comment]
> Easiest way to get into the top contributor spot. Should've done it myself 🤦

all part of the plan @noisekit 😆

**Pull request merged**
